/**
 * Regenerates src/shared/brand-logo.ts from public/logo-po-motivation.png.
 *
 * The logo has to be embeddable in a mail client and in a downloaded PDF-less
 * HTML print, neither of which can resolve a relative asset URL, so it ships
 * as a data URI in the bundle rather than as a file reference.
 *
 *   node scripts/gen-logo.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

const png = readFileSync(resolve(root, 'public/logo-po-motivation.png'));
const base64 = png.toString('base64');

const out = `/**
 * Generated by scripts/gen-logo.mjs from public/logo-po-motivation.png.
 * Do not edit by hand — run \`node scripts/gen-logo.mjs\` instead.
 *
 * ${png.length} bytes of PNG, ${base64.length} characters of base64.
 */

export const BRAND_LOGO_DATA_URL = 'data:image/png;base64,${base64}';
`;

writeFileSync(resolve(root, 'src/shared/brand-logo.ts'), out);
console.log(`brand-logo.ts written — ${png.length} bytes -> ${base64.length} chars`);
